### ISSUE TITLE
implement a style frameworks

### ISSUE THREAD

**Issue by NandoGoulartt** [PhelipeLB/Crud-beer#12]
I like chakra, because there are already many structures ready. It will speed up the front development process.

1. tailwindcss - [https://tailwindcss.com/docs/installation](url)
2. chakra-ui - [https://chakra-ui.com/getting-started](url)

**Comment by OtavioSC** [comment]
i agree about chakra-ui

**Comment by daniloab** [comment]
do not close before merging pull request

**Comment by NandoGoulartt** [comment]
closed by #14
