### ISSUE TITLE
default colors to define

### ISSUE THREAD

**Issue by NandoGoulartt** [PhelipeLB/Crud-beer#13]
color sheme to defined

**Comment by vinibgoulart** [comment]
i thought in mustard yellow, to remember the beer

**Comment by OtavioSC** [comment]
Podemos usar algo assim, parecido com a Ze delivery https://coolors.co/ffbe0b-09090a-1f1f20-ffffff

**Comment by tverderesi** [comment]
My suggestion is this palette: https://color.adobe.com/color_theme_beer_crud-color-theme-21264067 

I have extracted it from a beer picture I found on pexels: https://www.pexels.com/photo/filled-clear-glass-995686/, this way I think we don't get to similar to Zé Delivery's color scheme.
